### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by BalintQ** [d-sektionen/blapp#1]
Hi!
I don't know what I did wrong but I can't run the app always some error pops up.
![Képernyőkép 2024-06-20 082316](https://github.com/d-sektionen/blapp/assets/123942752/3b67d3ca-d8d2-452d-911f-d92994569d86)
![Képernyőkép 2024-06-20 083236](https://github.com/d-sektionen/blapp/assets/123942752/0552bf49-c196-4747-b006-41b6d64460ce)
Thanks BalintQ

**Comment by YouKnowBlom** [comment]
This app is not maintained at all which unfortunately means we can't really provide much support for it. If you can verify that you're a member of the section then we can discuss further, otherwise you're on your own unfortunately.

**Comment by BalintQ** [comment]
OK thank for help anyway.

**Comment by Kesomannen** [comment]
Legends say BalintQ is still looking for a solution to this day
